# yaml 配置
version: "3.7"
services:
  redis5014:
    image: "redis:5.0.14"
    ports:
      - "26379:6379"
  mysql8019:
    image: "mysql:8.0.19"
    ports:
      - "23306:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "8357"
      MYSQL_DATABASE: "bluebell"
      MYSQL_PASSWORD: "8357"
    volumes:
      - ./init.sql:/data/application/init.sql
  bluebell_app:
    build: .
    command: sh -c "./wait-for.sh mysql8019:3306 redis5014:6379 -- ./bluebell_app ./conf/config.yaml"
    depends_on:
      - mysql8019
      - redis5014
    ports:
      - "8888:8357"